# Generated by Django 3.0.6 on 2020-07-01 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_tool', '0003_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='user_id',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='user',
            field=models.OneToOneField(db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.OneToOneField(db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token', to=settings.AUTH_USER_MODEL),
        ),
    ]
