# Generated by Django 3.0.6 on 2020-06-10 11:32
from django.contrib.auth.models import Group
from django.db import migrations

from shared.models import Role


def load_roles(*args, **kwargs):
    Group.objects.bulk_create([Group(name=role) for role in Role.ROLES])


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_roles)
    ]
