"""
Django settings for reporting_tool project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from shared.settings import *

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'reporting_tool',
    'recon_db_manager',
    'drf_yasg',
    'shared'
]


EMAIL_BACKEND = 'django.core.mail.backends.{}.EmailBackend'.format(
    os.environ.get('EMAIL_BACKEND', 'console')  # console, dummy, firebased, locmem, smtp
)
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = os.environ.get('EMAIL_PORT')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL')

INFO_EMAIL = os.environ.get('INFO_EMAIL')

ROOT_URLCONF = 'reporting_tool.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['{}/{}'.format(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'reporting_tool.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'shared.validators.TwoLowercasesPasswordValidator',
    },
    {
        'NAME': 'shared.validators.TwoUppercasesPasswordValidator',
    },
    {
        'NAME': 'shared.validators.TwoNumbersPasswordValidator',
    },
    {
        'NAME': 'shared.validators.SpecialCharacterPasswordValidator',
    },
]

AWS_IAM_USER_MANAGER = os.environ.get('AWS_IAM_USER_MANAGER',
                                      'shared.managers.DummyIaMUserManager')
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
AWS_IAM_USER_GROUP = os.environ.get('AWS_IAM_USER_GROUP', '')
AWS_CLIENT_PORTAL_BUCKET = os.environ.get('AWS_CLIENT_PORTAL_BUCKET')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
STORAGE_ROOT = '{}/{}/'.format(BASE_DIR, 'data')
MEDIA_ROOT = '{}/{}/'.format(BASE_DIR, 'media')


# Export http log aws bucket and key accordingly
AWS_EXPORT_HTTP_LOG_KEY = os.environ.get('AWS_EXPORT_HTTP_LOG_KEY')


# --- PAYMENTS SETTINGS --- #
TRIAL_PERIOD_DAYS = 30
CHARGE_EACH_N_DAYS = 30
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY')
USER_LICENSE_FEE = 29.9
DEVICE_LICENSE_FEE = 5.9
# --- PAYMENTS SETTINGS --- #


# --- INVOICE SETTINGS --- #
BANK_REFERENCE_CODE = 1038
IBAN = 'FI48 1778 3000 0065 95'
BIC = 'NDEAFIHH'
TERMS_OF_PAYMENT_DAYS = 14
INTEREST_RATE = 8  # in %
BANK_CONNECTION = ' Nordea FI48 1778 3000 0065 95 NDEAFIHH'
DOMICILE = 'Tampere'
# --- INVOICE SETTINGS --- #
