# Generated by Django 3.0.6 on 2020-06-08 12:32

from django.db import migrations


# time_created is considered redundant as it repeats created_dt objective


class Migration(migrations.Migration):

    dependencies = [
        ('recon_db_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='time_created',
        ),
    ]
