# Generated by Django 3.0.6 on 2020-06-10 11:59

from django.db import migrations

from recon_db_manager.models import Organization


# Root organization with name `Recon AI`
# is must be inserted on database initialization.
# All of the superusers will be attached to it.


def load_root_organization(*args, **kwargs):
    Organization.objects.create(name=Organization.ROOT)


class Migration(migrations.Migration):

    dependencies = [
        ('recon_db_manager', '0003_auto_20200610_1125'),
    ]

    operations = [
        migrations.RunPython(load_root_organization)
    ]
