# Generated by Django 3.0.6 on 2020-06-11 10:24

from django.db import migrations, models


# Field concerning user email confirmation is required to be present


class Migration(migrations.Migration):

    dependencies = [
        ('recon_db_manager', '0004_load_root_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
