# Generated by Django 3.0.6 on 2020-06-12 12:34

from django.db import migrations, models


# is_active is renamed to isEmailVerified


class Migration(migrations.Migration):

    dependencies = [
        ('recon_db_manager', '0005_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_column='isEmailVerified', default=False),
        ),
    ]
