# Generated by Django 3.0.6 on 2020-07-13 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recon_db_manager', '0009_auto_20200708_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('categories', models.ManyToManyField(db_table='ManufacturerCategories', to='recon_db_manager.Category')),
            ],
            options={
                'db_table': 'Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('description', models.TextField()),
                ('manufacturer', models.ForeignKey(db_column='manufacturerId', on_delete=django.db.models.deletion.PROTECT, to='recon_db_manager.Manufacturer')),
            ],
            options={
                'db_table': 'Devices',
            },
        ),
    ]
