# Generated by Django 3.0.6 on 2020-07-14 12:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon_db_manager', '0010_category_device_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='price',
        ),
        migrations.AddField(
            model_name='device',
            name='buying_price',
            field=models.DecimalField(db_column='buyingPrice', decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='images',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='product_number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='sales_price',
            field=models.DecimalField(db_column='salesPrice', decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='seo_description',
            field=models.TextField(db_column='seoDescription', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='seo_keywords',
            field=models.CharField(db_column='seoKeywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='seo_title',
            field=models.CharField(db_column='seoTitle', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
