# Generated by Django 3.0.6 on 2020-07-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon_db_manager', '0011_auto_20200714_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
