# Generated by Django 3.0.6 on 2020-07-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recon_db_manager', '0012_device_created_dt'),
        ('recon_db_manager', '0011_auto_20200716_0811'),
    ]

    operations = [
    ]
