# Generated by Django 3.0.6 on 2020-07-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recon_db_manager', '0013_merge_20200716_1201'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deviceimage',
            table='DeviceImages',
        ),
    ]
