# Generated by Django 3.0.6 on 2020-07-16 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recon_db_manager', '0014_auto_20200716_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='images',
        ),
        migrations.AlterField(
            model_name='deviceimage',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recon_db_manager.Device'),
        ),
    ]
