# Generated by Django 3.0.6 on 2020-07-16 13:36

from django.db import migrations, models
import recon_db_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('recon_db_manager', '0015_auto_20200716_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceimage',
            name='path',
            field=models.ImageField(upload_to=recon_db_manager.models._device_img_save_path),
        ),
    ]
