# Generated by Django 3.0.6 on 2020-07-21 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recon_db_manager', '0016_auto_20200716_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.ForeignKey(db_column='categoryId', null=True, on_delete=django.db.models.deletion.PROTECT, to='recon_db_manager.Category'),
        ),
    ]
