# Generated by Django 3.0.6 on 2020-08-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon_db_manager', '0021_organization_created_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aws_access_key_id',
            field=models.CharField(db_column='awsAccessKeyId', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='aws_secret_access_key',
            field=models.CharField(db_column='awsSecretAccessKey', max_length=255, null=True),
        ),
    ]
