# Generated by Django 3.0.6 on 2020-08-18 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recon_db_manager', '0022_auto_20200818_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedobjects',
            name='file',
            field=models.ForeignKey(db_column='fileId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recon_db_manager.FileStorage'),
        ),
    ]
