# Generated by Django 3.0.6 on 2020-08-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recon_db_manager', '0023_auto_20200818_1458'),
        ('recon_db_manager', '0023_recurrentcharge'),
    ]

    operations = [
    ]
