# Generated by Django 3.0.6 on 2020-08-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon_db_manager', '0025_organization_is_invoice_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrentcharge',
            name='is_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
