# Generated by Django 3.0.6 on 2020-08-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon_db_manager', '0026_recurrentcharge_is_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relevantdata',
            name='sensor_GPS_lat',
            field=models.DecimalField(blank=True, db_column='sensorGpsLat', decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='relevantdata',
            name='sensor_GPS_long',
            field=models.DecimalField(blank=True, db_column='sensorGpsLong', decimal_places=7, max_digits=10, null=True),
        ),
    ]
