# Generated by Django 3.0.6 on 2020-08-31 11:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recon_db_manager', '0027_auto_20200828_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typecode',
            name='value',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='relevantdata',
            name='ambient_weather_condition',
            field=models.ForeignKey(blank=True, db_column='ambientWeatherCondition', max_length=3, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relevant_data_ambient_weather', to='recon_db_manager.TypeCode', to_field='value'),
        ),
        migrations.AddField(
            model_name='relevantdata',
            name='cad_file_tag',
            field=models.ForeignKey(blank=True, db_column='cadFileTag', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recon_db_manager.FileStorage'),
        ),
        migrations.AddField(
            model_name='relevantdata',
            name='event',
            field=models.ForeignKey(blank=True, db_column='eventType', max_length=3, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relevant_data_event', to='recon_db_manager.TypeCode', to_field='value'),
        ),
        migrations.AddField(
            model_name='relevantdata',
            name='face',
            field=models.ForeignKey(blank=True, db_column='face', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relevant_data_face', to='recon_db_manager.FileStorage'),
        ),
        migrations.AddField(
            model_name='relevantdata',
            name='license_plate',
            field=models.ForeignKey(blank=True, db_column='licensePlate', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relevant_data_license_plate', to='recon_db_manager.FileStorage'),
        ),
        migrations.AddField(
            model_name='relevantdata',
            name='lisence_plate_number',
            field=models.CharField(blank=True, db_column='lisencePlateNumber', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='relevantdata',
            name='object_class',
            field=models.ForeignKey(blank=True, db_column='objectClass', max_length=3, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recon_db_manager.TypeCode', to_field='value'),
        ),
        migrations.AddField(
            model_name='relevantdata',
            name='pedestrian_flow',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='pedestrianFlow', null=True),
        ),
        migrations.AddField(
            model_name='relevantdata',
            name='road_weather_condition',
            field=models.ForeignKey(blank=True, db_column='roadWeatherCondition', max_length=3, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relevant_data_road_weather', to='recon_db_manager.TypeCode', to_field='value'),
        ),
        migrations.AddField(
            model_name='relevantdata',
            name='stopped_vehicle_detection',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='stoppedVehicleDetection', null=True),
        ),
        migrations.AddField(
            model_name='relevantdata',
            name='traffic_flow',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='trafficFlow', null=True),
        ),
    ]
