# Generated by Django 3.0.6 on 2020-08-31 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recon_db_manager', '0028_auto_20200831_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relevantdata',
            old_name='lisence_plate_number',
            new_name='license_plate_number',
        ),
    ]
