# Generated by Django 3.0.6 on 2020-09-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon_db_manager', '0031_relevantdata_vehicle_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevantdata',
            name='ambient_temperature',
            field=models.DecimalField(blank=True, db_column='ambientTemperature', decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='relevantdata',
            name='road_temperature',
            field=models.DecimalField(blank=True, db_column='roadTemperature', decimal_places=2, max_digits=5, null=True),
        ),
    ]
