# Generated by Django 3.0.6 on 2020-09-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon_db_manager', '0032_auto_20200901_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinstance',
            name='gps_lat',
            field=models.DecimalField(blank=True, db_column='gpsLat', decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='gps_long',
            field=models.DecimalField(blank=True, db_column='gpsLong', decimal_places=7, max_digits=10, null=True),
        ),
    ]
