# Generated by Django 3.0.6 on 2020-09-28 11:22

from django.db import migrations

from recon_db_manager.models import TypeCode


def moist_to_wet(*args):
    wet = TypeCode.objects.get(value='WET')
    wet.short_description = 'Wet'
    wet.save()


class Migration(migrations.Migration):

    dependencies = [
        ('recon_db_manager', '0037_auto_20200921_1442'),
    ]

    operations = [
        migrations.RunPython(moist_to_wet)
    ]
