# Generated by Django 3.0.6 on 2020-10-28 08:53

import uuid
from django.db import migrations, models

from recon_db_manager.models import RelevantData


def create_uuid(apps, schema_editor):
    for item in RelevantData.objects.all():
        item.uuid = uuid.uuid4()
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('recon_db_manager', '0038_auto_20200928_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevantdata',
            name='uuid',
            field=models.UUIDField(editable=True, blank=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='relevantdata',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, blank=False, null=False)
        )
    ]
